name: build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  source:
    name: Build source package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker://python
        with:
          args: 'sh -c "pip install build && python -m build --sdist"'

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  wheels:
    name: Build binary packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Setup gfortran for macOS x86/arm64
        if: matrix.os == 'macos-latest'
        run: |
          BUILDING_ARCH=$(echo $CIBW_BUILD | cut -d '-' -f -2)
          echo "This is the CIBW_BUILD"
          echo $CIBW_BUILD
          echo "This is the arch"
          echo $BUILDING_ARCH
          if [ "$BUILDING_ARCH" == "x86_64" ]; then
              export CIBW_ENVIRONMENT_MACOS="F77=gfortran-11 F90=gfortran-11"
              echo $CIBW_ENVIRONMENT_MACOS
              echo "CIBW_ENVIRONMENT_MACOS=$CIBW_ENVIRONMENT_MACOS" >> $GITHUB_ENV
          elif [ "$BUILDING_ARCH" == "arm64" ]; then
            curl -L -O https://github.com/isuruf/gcc/releases/download/gcc-10-arm-20210728/gfortran-darwin-arm64.tar.gz
            sudo mkdir -p /opt/
            sudo cp "gfortran-darwin-arm64.tar.gz" /opt/gfortran-darwin-arm64.tar.gz
            pushd /opt
                  sudo tar -xvf gfortran-darwin-arm64.tar.gz
                  sudo rm gfortran-darwin-arm64.tar.gz
            popd
            export FC_ARM64="$(find /opt/gfortran-darwin-arm64/bin -name "*-gfortran")"
            libgfortran="$(find /opt/gfortran-darwin-arm64/lib -name libgfortran.dylib)"
            libdir=$(dirname $libgfortran)
            export FC_ARM64_LDFLAGS="-L$libdir -Wl,-rpath,$libdir"
            export SDKROOT=$(xcrun -sdk macosx --show-sdk-path) 
            export CIBW_ENVIRONMENT_MACOS="FC=$FC_ARM64 F90=$FC_ARM64 F77=$FC_ARM64 LDFLAGS=\" -arch arm64 $FC_ARM64_LDFLAGS\" CFLAGS=\" -arch arm64\" CXXFLAGS=\" -arch arm64\" CPPFLAGS=\" -arch arm64\" _PYTHON_HOST_PLATFORM=macosx-11.0-arm64 ARCHFLAGS=\" -arch arm64\" FCFLAGS=\" -arch arm64\" CROSS_COMPILING=1 host_alias=aarch64-apple-darwin20.0.0  MACOSX_DEPLOYMENT_TARGET=11.0 SDKROOT=$SDKROOT"
            echo $CIBW_ENVIRONMENT_MACOS
            echo "CIBW_ENVIRONMENT_MACOS=$CIBW_ENVIRONMENT_MACOS" >> $GITHUB_ENV
          fi
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14
        env:
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_BEFORE_ALL_MACOS: "brew install gfortran && brew unlink gfortran && brew link gfortran && chmod +x "${GITHUB_WORKSPACE}/.github/workflows/before_build.sh" && ./${GITHUB_WORKSPACE}/.github/workflows/before_build.sh && echo $CIBW_ENVIRONMENT_MACOS"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_TEST_SKIP: "*-macosx_arm64"
          # Skip musllinux wheels, which take a long time to build because Numpy must be built from source
          # Skip PyPy wheels
          # Skip 32-bit Intel wheels
          CIBW_SKIP: "*musllinux* pp* *_i686"
          CIBW_BUILD_VERBOSITY: "3"

      - uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: [source, wheels]
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
